### ISSUE TITLE
Ability to Edit People during "first time checkin" who are aged out

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#100]
Comment from KidSpring:  If we accidentally add a person and type in the wrong DOB as we add a new family, if the DOB ages them where they don't fit in a KidSpring environment, there's no way to go back and edit the DOB. We would just start again and add the child again to the family & end up with a duplicate. We would have fewer duplicates if there was a way to edit info for someone even if they didn't meet the age requirements for a KS room.

**Comment by dcs619** [comment]
@FrankGrand Couple thoughts:
1. This shouldn't be an issue with the current age now being displayed on the Add Person screen.
2. Selecting a "hidden" person to click an Edit Info button is a completely different UI pattern/nightmare
3. Add Person would search for the person that they added, but there's no control to allow inline editing.  This may be an option in the future but I don't see it being built by launch.

**Comment by FrankGrand** [comment]
@dcs619 This definitely isn't a "have to have" for launch.  Just wanted to document it.  Showing the age may help, ultimately they can go to Rock itself to fix, or just make a note to clean up the duplicate.  Would be something to keep on the list to have a way of handling from check-in at some point in future.

**Comment by dcs619** [comment]
I've added an Edit Info button to the Family Select screen, but there's no pattern to edit a "hidden" person.  If they want to edit that person's info, they need to show everyone.
