### ISSUE TITLE
Get volunteer/attendee structure for NS College and Central

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock-Plugins#108]

**Comment by FrankGrand** [comment]
NewSpring College
     -Acts
     -All-Staff
     -Bible
     -Builders and Shepherds
     -Character Forum
     -Christian Beliefs I
     -Christian Beliefs II
     -Communication
     -Ephesians
     -Leadership Forum
     -Leadership I
     -Small Group
     -Working Group

will work on central

**Comment by FrankGrand** [comment]
On staging rock, I've set up Central and New Serve which we need to add to each campus.  New Serve is under Anderson -> Next Steps Attendee
