### ISSUE TITLE
Update volunteer/attendee structure for NS College and Central

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock-Plugins#113]
NewSpring College
-Acts
-All-Staff
-Bible
-Builders and Shepherds
-Character Forum
-Christian Beliefs I
-Christian Beliefs II
-Communication
-Ephesians
-Leadership Forum
-Leadership I
-Small Group
-Working Group

Next Steps changes:
![screenshot 2015-04-06 14 52 37](https://cloud.githubusercontent.com/assets/1210933/7010043/9b6f7e56-dc6c-11e4-9d76-15ad8a31d42d.png)

Central changes:
![screenshot 2015-04-06 14 53 51](https://cloud.githubusercontent.com/assets/1210933/7010097/da16e4fa-dc6c-11e4-974e-f459a22f86c8.png)

**Comment by dcs619** [comment]
@FrankGrand where did we land on NewSpring College hierarchy?  It would help me to lump them in with Central since they don't apply to every campus

**Comment by FrankGrand** [comment]
@dcs619 I think this should live in it's own Group Type (Check In Config)
