### ISSUE TITLE
Fix SpecialNeeds Age Assignment

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#115]
Instead of FirstOrDefault, assign kids to Special needs room by best age fit

**Comment by dcs619** [comment]
This line needs to select the closest group based on age instead of the first or default 
https://github.com/NewSpring/Rock-Plugins/blob/develop/cc.newspring.AttendedCheckIn/Workflow/Action/CheckIn/SelectByBestFit.cs#L115
