### ISSUE TITLE
Cutting per "job" instead of every tag

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#116]
Need to think about possibility of this functionality (cutting after the whole family is done) for launch.  Think we will be having multiple check-in machines sharing printers, so cutting after every tag could get messy?

**Comment by dcs619** [comment]
Yep, there's not a good solution yet. See https://github.com/SparkDevNetwork/Rock/issues/831

**Comment by dcs619** [comment]
Potentially fixed, related to #132

**Comment by dcs619** [comment]
This looks like it might be in the label configuration.  
![image](https://cloud.githubusercontent.com/assets/1210933/8765874/94693e46-2df0-11e5-8597-21bedc0fa35d.png)

**Comment by FrankGrand** [comment]
David got it fixed!
