### ISSUE TITLE
Can't edit volunteer assignments with attended check-in

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#145]
When trying to edit a volunteer assignment, it will allow me to select any group I want, but when I try to select the schedule for the new attendance, I can't click on anything.

So in short there is no way to edit volunteer assignments.

**Comment by dcs619** [comment]
This should be fixed in beta.  Can you QA?

**Comment by dcs619** [comment]
Fixed in latest
