### ISSUE TITLE
Check-In Configurations are showing up that don't have any active schedules

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#147]
My understanding was that the Check-In Types shouldn't be showing up when no groups for that type have an active schedule.  Currently I can select a check-in Type with no schedules and it will let me proceed to search.  In this example, AND - Guest Services Attendee does not have an active schedule.
![screenshot 2015-06-07 at 5 53 01 pm](https://cloud.githubusercontent.com/assets/6911214/8026280/2364d336-0d3e-11e5-9190-61a07bab8fc8.png)

But I can still select it search for a family, but it always says:
![screenshot 2015-06-07 at 5 54 32 pm](https://cloud.githubusercontent.com/assets/6911214/8026287/430b6088-0d3e-11e5-9f96-d93cd408b89d.png)

**Comment by dcs619** [comment]
Added code to exclude types without schedules.
