### ISSUE TITLE
Left Sidebar stops working with new Rock theme

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#151]
The left sidebar navigation has issues when certain stuff happens in page. Jon Horton has details

**Comment by briankalwat** [comment]
@jonhorton can we chat about this when you have a second?

**Comment by jonhorton** [comment]
@briankalwat Yes we need to fix this :) We can chat as soon as I'm out of this meeting!

For what it's worth, it seems to be js related whenever you click another show/hide button on the page—it prevents the nav from working.

**Comment by dcs619** [comment]
Pretty sure this is fixed.

**Comment by jonhorton** [comment]
Yep this is fixed!

On Wed, Aug 12, 2015 at 10:40 AM, David Stevens notifications@github.com
wrote:

> Pretty sure this is fixed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/NewSpring/Rock-Plugins/issues/151#issuecomment-130324925
> .

## 

Jon Horton
Central Web Director
NewSpring Church
www.newspring.cc
Office: 864.965.9518
Cell: 919.218.6655
