### ISSUE TITLE
My Workflows Page

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#152]
The My Workflows pages look really off. The "Initiated By Me," "Assigned to Me," etc buttons overlap and if you are admin and have all of the workflows showing, the number icons get overlapped as well. Also, when a workflow button is selected it turns black and you can't read the text on the button.
![screen_shot_20150714_at_4 29 06_pm](https://cloud.githubusercontent.com/assets/6911214/8684817/79572bc8-2a48-11e5-99ee-355d9e6aab39.png)

**Comment by dcs619** [comment]
@briankalwat fixed in latest
