### ISSUE TITLE
Theme: My Profile link isn't available

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#154]
Even after clearing Rock cache, the options under My profile picture aren't showing up from the home/landing page.

![screenshot 2015-07-20 at 8 35 41 am](https://cloud.githubusercontent.com/assets/6911214/8775860/54884b3a-2eba-11e5-8761-8c9d4a56ec62.png)

**Comment by dcs619** [comment]
Fixed in latest theme release.
