### ISSUE TITLE
Badge Bar Right Aligning?

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#155]
Seems like the badge bar should be right justified instead of having all the blank space?
![screenshot 2015-07-20 at 8 40 07 am](https://cloud.githubusercontent.com/assets/6911214/8775936/0a3b9202-2ebb-11e5-96e8-af49ba3bb799.png)

**Comment by briankalwat** [comment]
@FrankGrand this is expected behavior - I can talk you through it if you're interested and we can talk about other options if you have suggestions! :dancer:
