### ISSUE TITLE
Group Viewer Page Issue

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#156]
When looking at the Group Viewer page, when looking at any of the group types, the label for the group name overlaps with the star you can click to "follow" the group. 

![screenshot 2015-07-20 at 8 44 19 am](https://cloud.githubusercontent.com/assets/6911214/8775991/8d36cd0c-2ebb-11e5-9d9d-e726a90e1016.png)

**Comment by dcs619** [comment]
@briankalwat fixed in latest
