### ISSUE TITLE
Group Structure Changes for Script

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#162]
David, 

Guest Services:
HR Team?.  
Have Special Event Attendee and Volunteer, under the Guest Services Volunteer Group Type, that needs to be moved to Attendee Type.  
Add Hispanic Team.

Fuse:
Jump Off is now VIP Room

Next Steps:
New Serve Participant?

KidSpring:
Make sure new Nursery/Preschool Structure is there

**Comment by dcs619** [comment]
Special Event Volunteer is under Guest Services Attendee?  Isn't that confusing?

Hispanic Team is under Guest Services Volunteer?

New KidSpring structure is a large enough task it should be by itself.
