### ISSUE TITLE
Discrepancy with attribution for Pledges

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#174]
Need to look at how pledges are getting attributed and how that is showing up with the Pledge Analytics tools.  Specific example is that it looks like my household pledge for step up in F1 got attributed to my wife in Rock, but on the pledge analytics tool, my name is coming up as having pledged.

**Comment by dcs619** [comment]
You'd have to ask Jon E. how pledges are attributed.  Maybe they are using
the "male head of house" as the criteria for what to display.

David Stevens

_Web Developer_NewSpring Church
www.newspring.cc

**Comment by FrankGrand** [comment]
Figured out that "giving leader" in family gets displayed in reporting tools.
