### ISSUE TITLE
Is Special Needs should read Has Special Needs

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#189]
Need to investigate if we can just change the attribute name, without any ramifications, or if other code changes would be affected.

**Comment by dcs619** [comment]
There are multiple instances of "IsSpecialNeeds" referenced in code throughout check-in.  Additionally this is a core attribute so I don't think we should change it.

**Comment by FrankGrand** [comment]
Fixed, just changed the name of the attribute and left the Key IsSpecialNeeds
