### ISSUE TITLE
Guest Services Group Changes for Conversion Script

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#194]
Add "Area Leader" group

"Service Coordinator" group renamed to "Service Leader"

"Service Leader" Job to "Team Leader"

**Comment by dcs619** [comment]
@FrankGrand all the current service leader roles are under KS, so should those change too?

**Comment by dcs619** [comment]
Guest Services only has a Service Coordinator position.  No Service Leader under GS and KS does not have a Service Coordinator
