### ISSUE TITLE
Family Page: Visitor list's previous button selects all visitors when they are left unselected.

### ISSUE THREAD

**Issue by BEGamache** [NewSpring/Rock-Plugins#57]
When I get to the families screen, when I click next under visitors and then the back button to see the first list of visitors all the visitors get selected. Once you deselect the person(s) then click next and back it maintains the proper selection until you select another family. Not a big issue, just something I noticed.

**Comment by dcs619** [comment]
Fixed in fa4a52a5d892c445b67bafbf13ec9ec452a191d1
