### ISSUE TITLE
Check-In Button Colors

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#77]
There could be some confusion over when you unselect a button.  It stays darkened until you click another button or off the button somewhere on the screen.  Is this how it's supposed to work?
![screenshot 2015-02-25 at 1 47 40 pm](https://cloud.githubusercontent.com/assets/6911214/6377815/00ea4f1e-bcf5-11e4-986e-2b62ec6f2a65.png)
![screenshot 2015-02-25 at 1 47 31 pm](https://cloud.githubusercontent.com/assets/6911214/6377816/00fb84f0-bcf5-11e4-900c-6937d62fe265.png)
![screenshot 2015-02-25 at 1 47 16 pm](https://cloud.githubusercontent.com/assets/6911214/6377817/01021a18-bcf5-11e4-89f7-568d3302205a.png)

**Comment by dcs619** [comment]
Fixed in 9574e58f8d555e95b849a4e538cefcc9f01ea774
