### ISSUE TITLE
Confirm Design of Check-In Label/Parent Receipt Label

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#85]
Need to nail down everything with the check-in labels

**Comment by FrankGrand** [comment]
Need to finish the allergy note/legal note combination.....KidSpring wants attention brought to Allergy note (Bold, or bigger font, or asterisk) doesn't necessarily care about legal note being bold or whatever

**Comment by dcs619** [comment]
Fixed with 1157451f8d5f2279090b178bda5e6f2778bc6be1
