### ISSUE TITLE
Migration: Remove SpecialNeeds from AbilityLevel list

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock-Plugins#87]

**Comment by ghost** [comment]
I do not see this in the migration or searching GitHub for "Special Needs".  The only place I see this ability is in the Azure database backup copy.  My "clean" database doesn't have this ability level.

**Comment by ghost** [comment]
@dcs619 do you mean you want me to write into the migration an explicit delete if it somehow does exist?

**Comment by FrankGrand** [comment]
@benwiley Not sure what David was meaning, but Special Needs was an ability level I added.
