### ISSUE TITLE
Research ways to reuse attendance code on subsequent check-in

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Rock-Plugins#95]

**Comment by dcs619** [comment]
If the attendance code DOESN'T change, that benefits us since it is how F1 works now.

**Comment by dcs619** [comment]
Per @benwiley the code changes every time. Closing.

**Comment by FrankGrand** [comment]
@dcs619 What would it take for it not to change?  This may be an issue KidSpring really wants to investigate

**Comment by dcs619** [comment]
This would require a rewrite of Workflow/Action/Checkin/SaveAttendance

**Comment by ghost** [comment]
@dcs619 I concur... do you want me to rewrite it?

**Comment by richarddubay** [comment]
This will be determined by how we handle checkout.  The code should change if they checkout and then in again.

**Comment by dcs619** [comment]
Researched, it is possible and require rewriting SaveAttendance but core team raised a security issue on SocialCast.  They would not want the option in core.

"For example, if you had a custody situation where only one parent was allowed to pick up the child, you wouldn't want any other check-in to use the same code."

Resolution:
For now we will depend on the Checked In display to fix mistakes. KidSpring will have to update their process when a parent loses their tag.
