### ISSUE TITLE
Research ways to find/show if a child is checked in 

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#97]
This may be related to how we figure out how to "checkout"

Yes ^

**Comment by dcs619** [comment]
Should be capable if the Calculate Last Attended is added to the person search workflow AND the CheckInPerson.LastAttended is set to today's date.

If so, would need to add the CLA action to the check-in migration and update the UI to include a FA icon when today's date matches.

**Comment by dcs619** [comment]
Per Frank, it'd be better to show a checkbox on the confirmation screen.  Then the Delete box would also check them out of that location/service. 

We need to set something in Select By Multiple Attended since that's the only place we're looking up prior attendances.

**Comment by dcs619** [comment]
Related to #70

**Comment by dcs619** [comment]
Fixed in 81ea19b864a3891dd4e4ee4d32a08150040a5efc
