### ISSUE TITLE
Add Allergy/Notes into New Person/Visitor modal

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#98]
Comment from KidSpring: Can we move the Allergy/Notes info to the same box where we enter birthdate, gender & grade? I feel it makes more sense to have it there when adding a new person to the system vs. after their info is in and we're in the middle of checking them in.

**Comment by dcs619** [comment]
@FrankGrand My only hesitation with this change is consistency...the New Person/Visitor modal has vertical space to add Allergy and Notes, but if you're adding a New Family there's not enough vertical or horizontal space to add them.

**Comment by FrankGrand** [comment]
@dcs619 I don't think this is something they will ultimately fight to have for launch, but I do think this would be one of the highest priorities for handling outside of launch requirments.  In thinking through what needs to be quickly put into first time check-in for the purposes of getting a kid a tag, allergy notes are high on the list.  It's not ideal to have to enter some info, then get them a room assignment, then have to edit that assignment to be able to add the allergy/note the first time.

**Comment by dcs619** [comment]
Per Frank, New Family is not a must-have but it would help if we can add it to the Add Visitor/Person modal and they can train volunteers in use cases.

**Comment by dcs619** [comment]
Fixed in c06085ee2a0920d5dbc84bbd8b8c82972612da1c
