### ISSUE TITLE
Show Age when DOB is selected via JS

### ISSUE THREAD

**Issue by FrankGrand** [NewSpring/Rock-Plugins#99]
Comment from KidSpring:  As we're typing in the person's DOB, can it auto calculate what age that child is right there on the screen. There are often times when grandparents or a neighbor know a child's birthday and age, but they're not sure of the year. This puts pressure on the check-in volunteer to do some quick math and most of the time they get it wrong & would have to continue going back into "Edit" to try again.

**Comment by dcs619** [comment]
May need to run UI pattern past Brian or James to see what looks best
